# Generated by Django 3.1 on 2021-04-21 02:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=49, verbose_name='文章标题')),
                ('image', models.ImageField(blank=True, upload_to='home/%Y%m%d%H%M%S', verbose_name='上传图片')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='文章详情')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
                'db_table': 'tb_article',
            },
        ),
    ]
