# Generated by Django 3.1 on 2021-04-21 02:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210421_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '家装知识管理', 'verbose_name_plural': '家装知识管理'},
        ),
        migrations.AlterField(
            model_name='article',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文章标题'),
        ),
    ]
