# Generated by Django 3.1 on 2021-04-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.category', verbose_name='选择分类'),
        ),
    ]
