# Generated by Django 3.1 on 2021-04-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210422_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecategory',
            name='homeImage',
            field=models.ImageField(upload_to='home/%Y%m%d%H%M%S', verbose_name='主图片'),
        ),
    ]
