# Generated by Django 3.1 on 2021-04-22 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210422_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homecategory', to='home.location', verbose_name='所在城市'),
        ),
    ]
