# Generated by Django 3.1 on 2021-04-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210422_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='home/videos/%Y%m%d%H%M%S', verbose_name='视频上传'),
        ),
    ]
