# Generated by Django 3.1 on 2021-04-25 07:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homecategory_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecategory',
            name='desc_pack',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='home_desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='介绍说明'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to='home/videos/%Y%m%d%H%M%S', verbose_name='视频上传(非必传)'),
        ),
    ]
