# Generated by Django 3.1 on 2021-04-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210425_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='bannerOne',
            field=models.ImageField(default='', upload_to='home/%Y%m%d%H%M%S', verbose_name='轮播图一(非必传)'),
        ),
        migrations.AddField(
            model_name='homecategory',
            name='bannerSecond',
            field=models.ImageField(default='', upload_to='home/%Y%m%d%H%M%S', verbose_name='轮播图二(非必传)'),
        ),
    ]
