# Generated by Django 3.1 on 2021-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210425_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='originPrices',
            field=models.FloatField(blank=True, default=0.0, verbose_name='原价格'),
        ),
    ]
