# Generated by Django 3.1 on 2021-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_homecategory_originprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='prices',
            field=models.FloatField(blank=True, default=0.0, verbose_name='现价格'),
        ),
    ]
