# Generated by Django 3.1 on 2021-04-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homecategory_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecategory',
            name='bannerOne',
            field=models.ImageField(blank=True, default='', null=True, upload_to='home/%Y%m%d%H%M%S', verbose_name='轮播图1(非必传)'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='bannerSecond',
            field=models.ImageField(blank=True, default='', null=True, upload_to='home/%Y%m%d%H%M%S', verbose_name='轮播图2(非必传)'),
        ),
    ]
