# Generated by Django 3.1 on 2021-04-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210425_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='地址详情'),
        ),
        migrations.AddField(
            model_name='homecategory',
            name='bossSay',
            field=models.CharField(default='', max_length=200, verbose_name='老板有话说'),
        ),
        migrations.AddField(
            model_name='homecategory',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='homecategory',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, verbose_name='精度'),
        ),
        migrations.AddField(
            model_name='homecategory',
            name='mobile',
            field=models.CharField(default='', max_length=100, verbose_name='商家电话，多个电话用,分割'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='bannerOne',
            field=models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='home/%Y%m%d%H%M%S78674', verbose_name='轮播图1(非必传)'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='bannerSecond',
            field=models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='home/%Y%m%d%H%M%S78674', verbose_name='轮播图2(非必传)'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='homeImage',
            field=models.ImageField(max_length=300, upload_to='home/%Y%m%d%H%M%S78674', verbose_name='主图片'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='video',
            field=models.FileField(blank=True, default='', max_length=300, null=True, upload_to='home/videos/%Y%m%d%H%M%S78674', verbose_name='视频上传(非必传)'),
        ),
    ]
