# Generated by Django 3.1 on 2021-04-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210426_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100)),
                ('session_key', models.CharField(max_length=100)),
                ('avatarUrl', models.CharField(blank=True, default='', max_length=300)),
                ('nickName', models.CharField(blank=True, default='', max_length=100, verbose_name='昵称')),
                ('gender', models.CharField(blank=True, default='', max_length=100, verbose_name='性别')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='国家')),
                ('province', models.CharField(blank=True, default='', max_length=100, verbose_name='省份')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='城市')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'tb_users',
            },
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='bannerOne',
            field=models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='home/%Y%m%d%H%M%S78391', verbose_name='轮播图1(非必传)'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='bannerSecond',
            field=models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='home/%Y%m%d%H%M%S78391', verbose_name='轮播图2(非必传)'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='homeImage',
            field=models.ImageField(max_length=300, upload_to='home/%Y%m%d%H%M%S78391', verbose_name='主图片'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='mobile',
            field=models.CharField(default='', max_length=100, verbose_name='商家电话'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='video',
            field=models.FileField(blank=True, default='', max_length=300, null=True, upload_to='home/videos/%Y%m%d%H%M%S78391', verbose_name='视频上传(非必传)'),
        ),
    ]
