# Generated by Django 3.1 on 2021-04-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210428_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecategory',
            name='poster',
            field=models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='home/%Y%m%d%H%M%S68731', verbose_name='上传海报(必传)'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='bannerOne',
            field=models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='home/%Y%m%d%H%M%S68731', verbose_name='轮播图1(非必传)'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='bannerSecond',
            field=models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='home/%Y%m%d%H%M%S68731', verbose_name='轮播图2(非必传)'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='homeImage',
            field=models.ImageField(max_length=300, upload_to='home/%Y%m%d%H%M%S68731', verbose_name='主图片'),
        ),
        migrations.AlterField(
            model_name='homecategory',
            name='video',
            field=models.FileField(blank=True, default='', max_length=300, null=True, upload_to='home/videos/%Y%m%d%H%M%S68731', verbose_name='视频上传(非必传)'),
        ),
    ]
